Repository minetest/minetest_docs, pull requests merged in 2022-01, with the labels that each got.

#2 Document the Lua environment
  doc/environment.adoc
Labels: discussion

#4 Standard sample template for wiki layout
  assets/pomegranate.png
  templates/standard.adoc
Labels: enhancement, discussion

#14 Document VoxelArea
  doc/VoxelArea.adoc
Labels: ready for review

#20 Standardize format and how to (discussion)
  HOWTO.adoc
  assets/pomegranate.png
  include/footer.adoc
  include/types.adoc
  templates/standard.adoc
Labels: discussion, meta

#29 HOWTO.adoc - Specify Admonition Usage and Basic Formatting Rules
  HOWTO.adoc
Labels: meta

#12 Document object properties
  doc/object_properties.adoc
  include/config.adoc
Labels: enhancement
